### ISSUE TITLE
Extraneous information?

### ISSUE THREAD

**Issue by ElectricLlama** [furmangg/automating-azure-analysis-services#2]
Is the section directly preceding this:

https://github.com/furmangg/automating-azure-analysis-services/blob/master/README.md#linkedserver

Extraneous? Currently you can process AAS using MSI authentication and don't need ClientID and ClientSecret - unless I misunderstood something. I see that these are included in the pipeline but I don't think it's required any more.

**Comment by furmangg** [comment]
There's a "ProcessAzureAS" and a "ProcessAzureAS MSI" pipeline. The MSI version was a fairly recent addition.

I'm not 100% sure which bit of the README you were talking about, but I did clean up one mention of MSI to make it clear that was talking about the ResumeAzureAS sample. You can see what I changed [here](https://github.com/furmangg/automating-azure-analysis-services/commit/b54d169a16638389a9e73205a2202dcf7add63dd#diff-04c6e90faac2675aa89e2176d2eec7d8). If that wasn't the part you were commenting on or don't feel I fixed the extraneous info, let me know.

Hope you find the samples useful. Thanks for the feedback about the documentation!

**Comment by ElectricLlama** [comment]
Oh I missed that I didn't realise there were two pipelines. But regarding ClientID and Client Secret, I'm definitely not using these in my current AAS REST pipeline
