### ISSUE TITLE
ADFv2/ProcessAzureAS MSI.json - HTTP request needs headers needed

### ISSUE THREAD

**Issue by erikatgaia** [furmangg/automating-azure-analysis-services#3]
Hi, for some reason I got an error now using this pipeline when trying to refresh AAS tabular model.
httpStatusCode: 415
I found out that headers were missing on the first web activity in the template:
I needed to add Content-Type: application/json on StartProcessingAzureAS, then it worked

Erik

**Comment by furmangg** [comment]
It seems to work with a hardcoded JSON body:
![image](https://user-images.githubusercontent.com/9261846/59363001-1693ac00-8cfa-11e9-8884-f334318aa8ef.png)

Are you using dynamic expressions? Do you maybe need to stick the json function around the dynamic string you build so that ADF knows it's json not a string you're posting?

````
@json(concat('{','my json here','}'))
````

**Comment by erikatgaia** [comment]
Ok, strange, I was also perplexed because it worked just two weeks ago, and now it stopped working. 
There is no dynamic expression in Body-field. I used the template ProcessAzureAS MSI.json without changes, that is
Body: {"Type":"Full","CommitMode":"transactional","MaxParallelism":10,"RetryCount":2}
But it works now for me when I added the headers. So no need to solve it for my sake, just wanted to post if anybody else experience the same problem
Thanks!

**Comment by alskaer** [comment]
I have setup an ADF - and after reading the thread i am very sure i have the correct ADF application id and tenant id listed into an admin group in my model. 

But i cannot get the StartProcessingAzureAS to work, and continues to get  "errorCode": "2108",
    "message": "{\"code\":\"Unauthorized...

The official doc lists that a oauth2 token needs to be in header, and the response sent out, does have an empty header for what i can see. [](https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-async-refresh). Is this be design?

The ResumeAzureAS flow works perfect.

**Comment by alskaer** [comment]
I am gonna leave my response here for all those who miss the point here. My issue is that i added the account to the MODEL security and not the SERVER sercurity! I failed to read the actual guide correctly. Works like a charm.
