### ISSUE TITLE
ADFV2 import template is giving error 

### ISSUE THREAD

**Issue by RsundararajanRTG** [furmangg/automating-azure-analysis-services#4]
Hi Greg when I try to import the Process Azure AS.json and try to save the Template I'm getting error saying invalid  can you please help. The error is it's not a valid template.
![error](https://user-images.githubusercontent.com/54039216/62891756-92b76980-bd14-11e9-8083-e5bf93b51f5b.png)

**Comment by furmangg** [comment]
I assume my other answer to issue #5 will help you. It’s not a template.

**Comment by RsundararajanRTG** [comment]
It worked !!!!! Thanks for your help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
