### ISSUE TITLE
Trying to import the ADFV2 JSON file

### ISSUE THREAD

**Issue by RsundararajanRTG** [furmangg/automating-azure-analysis-services#5]
Hi Gregg
I'm trying to import the Json and see the ADF flow. How can I import this JSON file. I'm very new to Azure data factory. Any help is appreciated.

**Comment by furmangg** [comment]
I’m away from my computer so let me know if my memory for button names fails me. If you create a new pipeline then rename it to match the one you are copying from JSON then you click View Code in the top right, you can paste my JSON over the top of that

**Comment by RsundararajanRTG** [comment]
Will try tomorrow and let you know

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
