### ISSUE TITLE
Cannot initialize the data source object of OLE DB provider "MSOLAP" for linked server "AZUREAS".

### ISSUE THREAD

**Issue by v-jinhet** [furmangg/automating-azure-analysis-services#7]
OLE DB provider "MSOLAP" for linked server "AZUREAS" returned message "The following system error occurred:  Sub or Function not defined".
Msg 7303, Level 16, State 1, Line 45
Cannot initialize the data source object of OLE DB provider "MSOLAP" for linked server "AZUREAS".

**Comment by furmangg** [comment]
I haven’t spent much time identifying exactly what driver install you need. But please install the MSOLAP amd64 version from:
https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-data-providers#download-the-latest-client-libraries-windows-installer

Keep me posted if that and restarting SQL Server doesn’t solve it. If it doesn’t solve it please share the SQL script you used to setup the linked server. Does the account used require multi-factor auth?
